// src/config/plans.js
// ─────────────────────────────────────────────────────────────────────────────
// Subscription plan definitions — NO imports, NO circular deps.
// Both subscription.controller.js and promoCode.controller.js import from here.
// ─────────────────────────────────────────────────────────────────────────────

export function getPlanCode(planId) {
  const map = {
    worker_pro: process.env.PAYSTACK_WORKER_PRO_PLAN_CODE,
    worker_enterprise: process.env.PAYSTACK_WORKER_ENT_PLAN_CODE,
    hirer_pro: process.env.PAYSTACK_HIRER_PRO_PLAN_CODE,
    hirer_enterprise: process.env.PAYSTACK_HIRER_ENT_PLAN_CODE,
    worker_pro_yearly: process.env.PAYSTACK_WORKER_PRO_YEARLY_PLAN_CODE,
    worker_enterprise_yearly: process.env.PAYSTACK_WORKER_ENT_YEARLY_PLAN_CODE,
    hirer_pro_yearly: process.env.PAYSTACK_HIRER_PRO_YEARLY_PLAN_CODE,
    hirer_enterprise_yearly: process.env.PAYSTACK_HIRER_ENT_YEARLY_PLAN_CODE,
  };
  return map[planId] || null;
}

export const WORKER_PLANS = [
  {
    id: "worker_free",
    tier: "FREE",
    name: "Free",
    price: 0,
    yearlyPrice: 0,
    currency: "NGN",
    billingCycle: "forever",
    stripePriceId: null,
    features: [
      "Apply to up to 15 jobs/month",
      "Basic profile listing",
      "3 portfolio images",
      "Standard search placement",
      "Basic messaging",
      "Community support",
    ],
    limits: {
      bidsPerMonth: 15,
      portfolioImages: 3,
      boosted: false,
      analytics: false,
      prioritySupport: false,
      teamAccounts: 0,
      apiAccess: false,
    },
  },
  {
    id: "worker_pro",
    tier: "PRO",
    name: "Pro Worker",
    price: 2500,
    yearlyPrice: 25000,
    currency: "NGN",
    billingCycle: "monthly",
    popular: true,
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_WORKER_PRO_PLAN_CODE,
    paystackYearlyCode: process.env.PAYSTACK_WORKER_PRO_YEARLY_PLAN_CODE,
    savings: "Save ₦5,000/year",
    features: [
      "Unlimited job applications",
      "⭐ Pro badge",
      "Boosted in search",
      "Up to 20 portfolio images",
      "Video intro on profile",
      "Earnings analytics",
      "Priority support",
      "Direct booking requests",
    ],
    limits: {
      bidsPerMonth: -1,
      portfolioImages: 20,
      boosted: true,
      analytics: true,
      prioritySupport: true,
      teamAccounts: 0,
      apiAccess: false,
    },
  },
  {
    id: "worker_pro_yearly",
    tier: "PRO",
    name: "Pro Worker",
    price: 25000,
    monthlyEquivalent: 2083,
    currency: "NGN",
    billingCycle: "yearly",
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_WORKER_PRO_YEARLY_PLAN_CODE,
    savings: "Save ₦5,000 vs monthly",
    badge: "Best Value",
    features: [
      "Unlimited job applications",
      "⭐ Pro badge",
      "Boosted in search",
      "Up to 20 portfolio images",
      "Video intro on profile",
      "Earnings analytics",
      "Priority support",
      "Direct booking requests",
      "🎁 2 months free vs monthly plan",
    ],
    limits: {
      bidsPerMonth: -1,
      portfolioImages: 20,
      boosted: true,
      analytics: true,
      prioritySupport: true,
      teamAccounts: 0,
      apiAccess: false,
    },
  },
  {
    id: "worker_enterprise",
    tier: "ENTERPRISE",
    name: "Enterprise Worker",
    price: 8000,
    yearlyPrice: 80000,
    currency: "NGN",
    billingCycle: "monthly",
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_WORKER_ENT_PLAN_CODE,
    paystackYearlyCode: process.env.PAYSTACK_WORKER_ENT_YEARLY_PLAN_CODE,
    savings: "Save ₦16,000/year",
    features: [
      "Everything in Pro",
      "🏆 Featured at top of category",
      "Team sub-accounts (up to 5)",
      "White-label invoices",
      "API access",
      "Dedicated account manager",
      "SLA support",
    ],
    limits: {
      bidsPerMonth: -1,
      portfolioImages: -1,
      boosted: true,
      analytics: true,
      prioritySupport: true,
      teamAccounts: 5,
      apiAccess: true,
    },
  },
  {
    id: "worker_enterprise_yearly",
    tier: "ENTERPRISE",
    name: "Enterprise Worker",
    price: 80000,
    monthlyEquivalent: 6667,
    currency: "NGN",
    billingCycle: "yearly",
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_WORKER_ENT_YEARLY_PLAN_CODE,
    savings: "Save ₦16,000 vs monthly",
    badge: "Best Value",
    features: [
      "Everything in Pro",
      "🏆 Featured at top of category",
      "Team sub-accounts (up to 5)",
      "White-label invoices",
      "API access",
      "Dedicated account manager",
      "SLA support",
      "🎁 2 months free vs monthly plan",
    ],
    limits: {
      bidsPerMonth: -1,
      portfolioImages: -1,
      boosted: true,
      analytics: true,
      prioritySupport: true,
      teamAccounts: 5,
      apiAccess: true,
    },
  },
];

export const HIRER_PLANS = [
  {
    id: "hirer_free",
    tier: "FREE",
    name: "Free",
    price: 0,
    yearlyPrice: 0,
    currency: "NGN",
    billingCycle: "forever",
    stripePriceId: null,
    features: [
      "Post up to 5 jobs/month",
      "Access full worker search",
      "Basic messaging",
      "3 saved searches",
      "Community support",
    ],
    limits: {
      jobPostsPerMonth: 5,
      boostedSearch: false,
      advancedFilters: false,
      analytics: false,
      teamAccounts: 0,
      apiAccess: false,
      bulkHiring: false,
    },
  },
  {
    id: "hirer_pro",
    tier: "PRO",
    name: "Pro Hirer",
    price: 3500,
    yearlyPrice: 35000,
    currency: "NGN",
    billingCycle: "monthly",
    popular: true,
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_HIRER_PRO_PLAN_CODE,
    paystackYearlyCode: process.env.PAYSTACK_HIRER_PRO_YEARLY_PLAN_CODE,
    savings: "Save ₦7,000/year",
    features: [
      "Unlimited job posts",
      "See verified workers first",
      "Advanced GPS radius filters",
      "Unlimited saved worker lists",
      "Priority worker matching",
      "⭐ Pro badge",
      "Job post analytics",
    ],
    limits: {
      jobPostsPerMonth: -1,
      boostedSearch: true,
      advancedFilters: true,
      analytics: true,
      teamAccounts: 0,
      apiAccess: false,
      bulkHiring: false,
    },
  },
  {
    id: "hirer_pro_yearly",
    tier: "PRO",
    name: "Pro Hirer",
    price: 35000,
    monthlyEquivalent: 2917,
    currency: "NGN",
    billingCycle: "yearly",
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_HIRER_PRO_YEARLY_PLAN_CODE,
    savings: "Save ₦7,000 vs monthly",
    badge: "Best Value",
    features: [
      "Unlimited job posts",
      "See verified workers first",
      "Advanced GPS radius filters",
      "Unlimited saved worker lists",
      "Priority worker matching",
      "⭐ Pro badge",
      "Job post analytics",
      "🎁 2 months free vs monthly plan",
    ],
    limits: {
      jobPostsPerMonth: -1,
      boostedSearch: true,
      advancedFilters: true,
      analytics: true,
      teamAccounts: 0,
      apiAccess: false,
      bulkHiring: false,
    },
  },
  {
    id: "hirer_enterprise",
    tier: "ENTERPRISE",
    name: "Enterprise",
    price: 20000,
    yearlyPrice: 200000,
    currency: "NGN",
    billingCycle: "monthly",
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_HIRER_ENT_PLAN_CODE,
    paystackYearlyCode: process.env.PAYSTACK_HIRER_ENT_YEARLY_PLAN_CODE,
    savings: "Save ₦40,000/year",
    features: [
      "Everything in Pro",
      "Bulk hiring dashboard",
      "Team accounts (up to 20)",
      "Dedicated account manager",
      "API integration",
      "SLA guarantee",
    ],
    limits: {
      jobPostsPerMonth: -1,
      boostedSearch: true,
      advancedFilters: true,
      analytics: true,
      teamAccounts: 20,
      apiAccess: true,
      bulkHiring: true,
    },
  },
  {
    id: "hirer_enterprise_yearly",
    tier: "ENTERPRISE",
    name: "Enterprise",
    price: 200000,
    monthlyEquivalent: 16667,
    currency: "NGN",
    billingCycle: "yearly",
    stripePriceId: null,
    paystackPlanCode: process.env.PAYSTACK_HIRER_ENT_YEARLY_PLAN_CODE,
    savings: "Save ₦40,000 vs monthly",
    badge: "Best Value",
    features: [
      "Everything in Pro",
      "Bulk hiring dashboard",
      "Team accounts (up to 20)",
      "Dedicated account manager",
      "API integration",
      "SLA guarantee",
      "🎁 2 months free vs monthly plan",
    ],
    limits: {
      jobPostsPerMonth: -1,
      boostedSearch: true,
      advancedFilters: true,
      analytics: true,
      teamAccounts: 20,
      apiAccess: true,
      bulkHiring: true,
    },
  },
];

export const FEATURED_PACKAGES = [
  {
    id: "featured_7days",
    name: "7-Day Spotlight",
    days: 7,
    price: 1500,
    currency: "NGN",
    type: "CATEGORY_TOP",
    availableFrom: "phase2",
  },
  {
    id: "featured_14days",
    name: "14-Day Boost",
    days: 14,
    price: 2500,
    currency: "NGN",
    type: "SEARCH_TOP",
    popular: true,
    availableFrom: "phase2",
  },
  {
    id: "featured_30days",
    name: "30-Day Premium",
    days: 30,
    price: 5000,
    currency: "NGN",
    type: "HOMEPAGE",
    availableFrom: "phase2",
  },
];

export const ALL_PLANS = [...WORKER_PLANS, ...HIRER_PLANS];
